name: Pages Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: 
  group: docs
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Collect-Ancillary-Files
        run: |
          gh release download 1m-gs-pmtiles -p bounds.geojson -O docs/1m/index.geojson
          gh release download 500k-gs-pmtiles -p bounds.geojson -O docs/500k/index.geojson
          gh release download 100k-gs-pmtiles -p bounds.geojson -O docs/100k/index.geojson
          gh release download 50k-gs-pmtiles -p bounds.geojson -O docs/50k/index.geojson

      - name: Upload-Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/'

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
